import { useState } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import  Button  from './styles'
import Confetti from 'react-confetti'
import YouTube from 'react-youtube';

export default function Home() {
  const [startConfetti, useConfetti] = useState(false)

  const handleClick = () => {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    useConfetti(true)
  }

  const opts = {
    height: "390",
    width: "640",
    playerVars: {
      autoplay: 1,
    },
  };

  const onPlayerReady = (event) => {
    // access to player in all event handlers via event.target
    event.target.pauseVideo();
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {startConfetti && (
          <>
            <Confetti/>
            <h1 className={styles.title}>
              HAPPY BIRTHDAY
            </h1>
            <YouTube videoId="dQw4w9WgXcQ" 
            opts={opts} onReady={onPlayerReady} />
          </>
        )}

        {!startConfetti &&(
          <>
            <h1 className={styles.title}>
            Is today your birthday?
            </h1>

            <Button onClick={handleClick}>Yes!!!!!!!!!!</Button>
          </>
        )}
      </main>


    </div>
  )
}
